version: "3.8"
services:
  app-prod:
    container_name: nestjs-prod
    image: nestjs-prod
    restart: unless-stopped
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: prod
    env_file:
      - ../.env.prod
    ports:
      - ${APP_OUTER_PORT}:${APP_PORT}
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: route_admin
      POSTGRES_USER: route_admin
      POSTGRES_DB: db_prod
    ports:
      - "5433:5432"
    volumes:
      - ./backups:/home/backups